version: '3.8'

services:
  # MongoDB Service
  mongoDB:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zoro
      - MONGO_INITDB_ROOT_PASSWORD=zoro

  # Mongo Express Service
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=zoro
      - ME_CONFIG_MONGODB_ADMINPASSWORD=zoro
      - ME_CONFIG_MONGODB_SERVER=mongoDB
      - ME_CONFIG_MONGODB_URL=mongodb://zoro:zoro@mongoDB:27017/?authSource=admin

  # Java Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    ports:
      - "8080:8080"
    depends_on:
      - mongoDB
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://zoro:zoro@mongoDB:27017/?authSource=admin

volumes:
  mongo: {}
