#  spring:
#    data:
#      mongodb:
#        host: mongoDB
#        port: 27017
#        database: chat_app
#        username: zoro
#        password: zoro
#        authentication-database: admin
#  server:
#    port: 8080



spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@mugiwara.arqsgzm.mongodb.net/?retryWrites=true&w=majority&appName=mugiwara
      database: mugiwara
server:
  port: 8080
